# Default airflow repository -- overridden by all the specific images below
defaultAirflowRepository: mareleite3/airflow

# Default airflow tag to deploy
defaultAirflowTag: "2.5.4"

# Airflow version (Used to make some decisions based on Airflow Version being deployed)
#airflowVersion: "2.6.2"
webserverSecretKey: e17a35e2ffedf93f1d753f053c6ecbf9
executor: "KubernetesExecutor"


dags:
  persistence:
    # Annotations for dags PVC
    annotations: {}
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    ## optional subpath for dag volume mount
    subPath: ~
  gitSync:
    enabled: false
    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/apache/airflow.git
    branch: v2-2-stable
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "tests/dags"
